### ISSUE TITLE
add plantuml examples

### ISSUE THREAD

**Issue by WolfgangFahl** [WolfgangFahl/pyMetaModel#16]
Try rendering 
https://raw.githubusercontent.com/WolfgangFahl/pyMetaModel/main/examples/family/FamilyContext.puml 
as outlined in https://stackoverflow.com/questions/32203610/how-to-integrate-uml-diagrams-into-gitlab-or-github  
![Family Context](http://www.plantuml.com/plantuml/proxy?cache=no&src=https://raw.githubusercontent.com/WolfgangFahl/pyMetaModel/main/examples/family/FamilyContext.puml)

**Comment by WolfgangFahl** [comment]
[png via diagrams.bitplan.com](http://diagrams.bitplan.com/render/png/0x190b815a.png)

**Comment by tholzheim** [comment]
[![https://diagrams.bitplan.com/render/png/0x79a1229e](https://diagrams.bitplan.com/render/png/0x79a1229e)](https://diagrams.bitplan.com/render/txt/0x79a1229e)

**Comment by WolfgangFahl** [comment]
![Scientific Events Context](http://www.plantuml.com/plantuml/proxy?cache=no&src=https://raw.githubusercontent.com/WolfgangFahl/pyMetaModel/main/examples/scientific-events/scientific-events_puml.txt)
